### ISSUE TITLE
Google group not accessible

### ISSUE THREAD

**Issue by litebito** [mangdangroboticsclub/QuadrupedRobot#14]
It seems that the google groups mentioned in the description
(https://groups.google.com/g/minipupper) are not accessible?

```
Content unavailable

Click here to try again.
If you've seen this page more than once, try switching accounts.
```

**Comment by axello** [comment]
I have the same problem.

**Comment by mangdangroboticsclub** [comment]
We move to the Facebook group now, please join our group, thanks!
https://www.facebook.com/groups/716473723088464
