### ISSUE TITLE
Software Installation

### ISSUE THREAD

**Issue by tractrac91** [mangdangroboticsclub/QuadrupedRobot#15]
With the pre-installed image the services for joystick and robot are running, but the robot doesn't move while running "calibrate_servos.py".

Therefore I tried to install a empty "ubuntu-18.04.5-preinstalled-server-arm64+raspi4.img" image and cloned and used the "MiniPupper_V2" repro. After installing bluez for bluetooth the connection to the PS4 controller works but for the robot services I get this error: 

`Traceback (most recent call last):
  File "run_robot.py", line 16, in <module>
    from src.Controller import Controller
  File "/home/ubuntu/QuadrupedRobot/StanfordQuadruped/src/Controller.py", line 2, in <module>
    from src.GaitScheme import GaitScheme
ImportError: /home/ubuntu/QuadrupedRobot/StanfordQuadruped/src/GaitScheme.so: undefined symbol: PyInterpreterState_GetID`

Are there other requirements besides bluez I need to manually install? Or should I use another software version?

**Comment by mangdangroboticsclub** [comment]
Per our discussion, please follow the below link at first, thanks!
https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/index.html
