### ISSUE TITLE
Mini Pupper WiFi

### ISSUE THREAD

**Issue by EdSeymore** [mangdangroboticsclub/QuadrupedRobot#17]
Do you have instructions for setting up the WiFi for the Mini Pupper?

**Comment by mangdangroboticsclub** [comment]
hi , 
    Please remove "dtoverlay=disable-wifi"  in /boot/firmware/syscfg.txt and reboot the device .  The wifi has been disabled by default .

**Comment by EdSeymore** [comment]
That seems to have worked. 

But, what I thought was the default login password from the pupper site is not working for ssh. ???

**Comment by EdSeymore** [comment]
I guessed the correct password.
