### ISSUE TITLE
Assembly Instructions instead of placeholders?

### ISSUE THREAD

**Issue by axello** [mangdangroboticsclub/QuadrupedRobot#18]
Hi,
It seems most assembly instructions, apart from the Legs video, are simply **placeholders** for missing, euh, _Assembly Instructions_

Do they still need to be copied from another repository, or are these documented elsewhere?

**Comment by Blackvenom** [comment]
Workaround:
If you Switch on top of minipupper GitHub Page from MiniPupper_V2 to MiniPupper_V1, you can see assembly instructions on the bottom:
https://drive.google.com/file/d/12Xbnqv3Rm7TEcjBZVSbVkBVNKNO3IOfm/view?usp=sharing

**Comment by tractrac91** [comment]
You can find newer instructions here: [https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/guide/Assembly.html](https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/guide/Assembly.html)

**Comment by mangdangroboticsclub** [comment]
Yes, about the documents, please follow the below link,
https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/index.html
