### ISSUE TITLE
ROS integration

### ISSUE THREAD

**Issue by JanezCim** [mangdangroboticsclub/QuadrupedRobot#2]
Hello! Really nice project! Is there any plan to connect it with ROS?

**Comment by mangdangroboticsclub** [comment]
For the ROS&SLAM&Navigation&ObstacleAvoidance Show, please refer to the below link,
https://youtu.be/WghufWRAieE
If you have any questions, please feel free to let us know.
Very appreciated if you give us some feedback or advice.
Thanks!

**Comment by JanezCim** [comment]
Ok, nice! If you could point me to any opensourced code that would allow ros control, that would be great!

**Comment by mangdangroboticsclub** [comment]
Please wait, we are still developing some ROS features, will be open-source after our crowdfunding campaign. Thanks!
