### ISSUE TITLE
Calibration Leg 4 Calf

### ISSUE THREAD

**Issue by klotzdafotz** [mangdangroboticsclub/QuadrupedRobot#24]
Image 20220109_v1.7.0_MiniPupper_V2_PS4_Ubuntu_21.10.0_Baseline.img.zip
Can't Calibrate Leg 4 Calf. It always moves to the previous position.
Angle Matrix
[-6.0, -9.0, 5.0, -6.0]
[56.0, 79.0, 56.0, 15.0]
[-38.0, -31.0, -35.0, -90.0]
It's the last value in the last row. Seems -90 is the maximum value.
I edited the code, now it updates with -98 and look fine. why is 90 max value in code?

**Comment by mangdangroboticsclub** [comment]
I have not found the issue, could you please double confirm your servo position?
You can check the detailed info at the below link, thanks!
https://www.facebook.com/groups/716473723088464
