### ISSUE TITLE
Display Backlight missing

### ISSUE THREAD

**Issue by smarthomeagentur** [mangdangroboticsclub/QuadrupedRobot#25]
Hi,
I am using pupper with ROS and it works fine so far. I managed to run lidar navigation and also could connect a pi camera. Is there a way to use the LCD Display? At the moment it boots with a text on it "Mini Pupper" and has no backlight. What is the smart way to control it on ROS?

Thanks and best regards

Daniel

**Comment by mangdangroboticsclub** [comment]
Great job!
Will update the source code and open it soon, please wait, thanks!

**Comment by mangdangroboticsclub** [comment]
About ROS&OpenCV image file， please refer to the below link,
https://drive.google.com/file/d/1gxisQQCIXHLqBpFs_-yun-ajLsee6gy8/view?fbclid=IwAR2fQYo_cQtz1-peqWscYlrh-9fbDLfSr5-KHBD-2XP_yfGMLI0qXtNWEIU

For the guide, please refer to the below link at first, thanks!
https://github.com/mangdangroboticsclub/minipupper_ros


In the ros image , Please turn to : ~/Mangdang/01-code/minipupper_ros_bsp/mangdang/LCD   and refer to demo.py
