### ISSUE TITLE
is there an updated build instruction

### ISSUE THREAD

**Issue by lein1013** [mangdangroboticsclub/QuadrupedRobot#26]
comparing the parts I got with the BOM I see that there are differences in length and size - e.g at the inserts and the standoffs
Is there an update build instruction available?

**Comment by axello** [comment]
I would like one as well! 
Even though I succeeded in putting the mini pupper together, I seem to be missing lots of 4 mm screws for the leg covers. 

I did discovered a newer manual online in Chinese, *with* all the necessary screw lengths. Their google drive is more up to date.
https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/guide/Assembly.html

**Comment by mangdangroboticsclub** [comment]
If your package is a basic kit, please follow the below document, it's new, same with your package.
(I will update the BOM list before this weekend.)
https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/index.html
Fusion 360 CAD model will be useful for you to understand, thanks!
https://a360.co/3CL8zoQ

**Comment by Danfoa** [comment]
@mangdangroboticsclub Please make these instructions link available in a more visible part. Hopefully in the README. It is not possible that users have to have luck to find the instructions.

**Comment by hubertsmits** [comment]
My apologies if I’m not logging this request correctly. I broke the LCD for the mini puppet (the 3D prints are pretty bad). How can I buy a replacement LCD?

— Hubert

**Comment by gilaramirez** [comment]
Can you please remove the instructions from this site's wiki page, as they are not correct. I spent hours trying to flash firmware unsuccessfully before I found the alternative website with the correct files. Please replace with a link to the maintained site.

**Comment by mangdangroboticsclub** [comment]
Sorry for the delay, already update the site's wiki page.
Please follow the document at the below link, thanks!
https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/index.html
