### ISSUE TITLE
Please supply cad files of the delivered kickstarter!

### ISSUE THREAD

**Issue by axello** [mangdangroboticsclub/QuadrupedRobot#27]
I want to make a base-on-a-stick, like in the examples and tutorials. For that it would be helpful if the CAD file of the baseplate was available. I want to 'click' it into place where the battery normally sits, but for that you need something with tabs which slide into place. 

Life would be easier if the baseplate design would be available.

**Comment by hubertsmits** [comment]
Axel,

Did you find this link for the Fusion360 files?

Fusion 360 CAD model: https://a360.co/3CL8zoQ

— Hubert

**Comment by mangdangroboticsclub** [comment]
Axel,
please find it at the below link, thanks!
https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/index.html
