### ISSUE TITLE
BOM file is in owner's bin - not available anymore

### ISSUE THREAD

**Issue by bojanpotocnik** [mangdangroboticsclub/QuadrupedRobot#29]
> BOM list: https://drive.google.com/file/d/18phJat8GdK5Yq5p4K1ZmfY1-nMf1lQw4/view?usp=sharing

results in 
![MiniPupperBOM](https://user-images.githubusercontent.com/4901762/154649250-dbec69fd-701b-43f6-84c9-3e7b3c0fc36c.png)

the same goes for file available here https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/reference/Design.html

**Comment by mangdangroboticsclub** [comment]
Sorry for my mistake, already OK now.
Thanks for your feedback.
