### ISSUE TITLE
Softwareinstallation pain

### ISSUE THREAD

**Issue by sffranke** [mangdangroboticsclub/QuadrupedRobot#30]
Hi, 
-Step 3: "_this version_ so everyone is using the same version" is not there, so I used the official image
-4. Verify everything is working leads to: Wifi is gone, see other issue here, is fixable but Bluetooth is not working (Failed to start discovery: org.bluez.Error.InProgress) 
-4. is follwed by 7. where is 5. and 6.

It looks promising, but the problems that arise are traditional.

**Comment by sffranke** [comment]
Tried it again, Bluetooth works until 3. Power-cycle the robot  
Anybody made it using ubuntu-18.04.5-preinstalled-server-arm64+raspi4.img ?
Any hints for me?

**Comment by mangdangroboticsclub** [comment]
hi , Mini Pupper working OS is ubuntu21.10.    In ubuntu-18.04.5, may be you'd better turn to MiniPupper branch  ,  but it  is not maintaied now.

**Comment by sffranke** [comment]
Hi, ok thank you for the information.
