### ISSUE TITLE
Wrong file format for images in cartoons folder

### ISSUE THREAD

**Issue by jensanjo** [mangdangroboticsclub/QuadrupedRobot#31]
Several images in `QuadrupedRobot/Mangdang/LCD/cartoons` have  a `.png` extensions: `logo.png`, `notconnect.png`, `turnaround.png`, `walk.png`, `walk_r1.png`.
But these are actually `jpg` files, which is confusing. Please convert them to `.png`.

**Comment by mangdangroboticsclub** [comment]
Already converted, many thanks for your feedback!
Will confirm and fix other feedback this week soon.
Looking forward to your more advice.
Best Regards
