### ISSUE TITLE
SLAM Installation & ISO Do Not Run

### ISSUE THREAD

**Issue by gilaramirez** [mangdangroboticsclub/QuadrupedRobot#32]
I tried following the instructions here:  
[https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/guide/SLAM.html](url).  I was able to set up the PC side.  The Raspberry Pi B4 will not run the ISO [https://drive.google.com/file/d/11zeivhN-fyTMdf6iuhcVD-Ib6aKj7s_5/view?usp=sharing](url) in the Google Drive site.  The Raspberry Pi reports newer software is required.

**Comment by mangdangroboticsclub** [comment]
I updated the document( https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/index.html )
Please download the below image
(64bit)v1.0.0.20220219.MiniPupper_V2_ROS&OpenCV_Ubuntu20.04.03.img
https://drive.google.com/drive/folders/12FDFbZzO61Euh8pJI9oCxN-eLVm5zjyi

and follow the below steps,
https://github.com/mangdangroboticsclub/minipupper_ros

Thanks!
