### ISSUE TITLE
Google drive link for Assembly instructions doesn't work

### ISSUE THREAD

**Issue by thaytan** [mangdangroboticsclub/QuadrupedRobot#33]
The link given for Assembly instructions in the README (https://drive.google.com/file/d/12Xbnqv3Rm7TEcjBZVSbVkBVNKNO3IOfm/view?usp=sharing) leads me to a 'Sorry, the file you have requested does not exist.' error.

![image](https://user-images.githubusercontent.com/74973/155527340-b3367b91-e975-4af2-8db7-174939c4d332.png)

**Comment by shot-codes** [comment]
There are assembly instructions in the docs [here](https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/guide/Assembly.html).

**Comment by mangdangroboticsclub** [comment]
Thanks, TheFoolishPupil.
Hi thaytan, please refer to the document at the below link, thanks!
https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/index.html
