### ISSUE TITLE
Missing Parts / Files / URDF / Specifications

### ISSUE THREAD

**Issue by Danfoa** [mangdangroboticsclub/QuadrupedRobot#34]
Good day, 

I have not received several of the parts advertised with the developer package, but what it is more concerning there is no information about these parts anywhere, making it impossible to buy them, or print them. 

Regarding missing parts information in the BOM Lists:
-  The 4 bearings/brushings used in the chassis of the robot are not listed, and its specifications are not known making it impossible to buy these parts (WHICH DID NOT COME WITH MY PACKAGE). Are these bearings? or brushings? please provide a link to them or at least their specifications.
![image](https://user-images.githubusercontent.com/8356912/155682982-cc61d000-216b-4697-bb2b-4f58aac0b5a3.png)

Regarding missing STL files:
- Robot feet. I did not receive the robot feet with my package, there is not 3D file to them, nor a mechanism for ordering them

**Can you share the Fusion360 assembly file, such that we can use it for more than visualization, that is, so we can use this assembly to obtain a URDF file and to properly make modifications to the robot parts, and assembly?.**

**Comment by shot-codes** [comment]
Hey @Danfoa, you can find the STL files [here](https://drive.google.com/drive/folders/1qY0D0EFMEq7hCxesOtWjdjGncZ6CRQnF). The link is from this page in the docs - https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/reference/Design.html

**Comment by mangdangroboticsclub** [comment]
Hi Danfoa,

Maybe you ignored our Kickstarter update, please refer to the below link, 
https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/index.html

You can also find the BOM list on the Kickstarter page and the detailed components information at the below link,
https://drive.google.com/file/d/18phJat8GdK5Yq5p4K1ZmfY1-nMf1lQw4/view

Thanks!
