### ISSUE TITLE
20220109_v1.7.0_MiniPupper_V2_PS4_Ubuntu_21.10.0_Baseline.img.zip - WIFI not recognized

### ISSUE THREAD

**Issue by gilaramirez** [mangdangroboticsclub/QuadrupedRobot#35]
After flashing 20220109_v1.7.0_MiniPupper_V2_PS4_Ubuntu_21.10.0_Baseline.img.zip I noted Wifi chip no longer recognized.
Tried to install 20211220_v2.1.3_MiniPupper_V2_PS4_Ubuntu_20.04.2_Baseline.img.zip and the board now says start4.elf is not recognized, this board needs newer software.

**Comment by mangdangroboticsclub** [comment]
@gilaramirez   hi , Thanks for your question .  

1) For 20220109_v1.7.0_MiniPupper_V2_PS4_Ubuntu_21.10.0_Baseline.img.zip .  Owning to performance , we disable the WIFI . You can enable it by remove "dtoverlay=disable-wifi" in /boot/firmware/syscfg.txt  and then reboot the device . by the way , the next ROM will enable WIFI by default.

2)The newest Pi4B can't boot up on  oldest ubuntu 20.04 . So , Please waive these ROM with ubuntu20.04.
