### ISSUE TITLE
no way to pair the PS4 joystick

### ISSUE THREAD

**Issue by FaboNo** [mangdangroboticsclub/QuadrupedRobot#38]
Hi there

I took the 20220109_v1.7.0_MiniPupper_V2_PS4_Ubuntu_21_10_0_Baseline.Img corresponding the V2 custom circuit board and  I did not get any problem for the installation.

I Run `sudo systemctl status joystick` and I got the following:
![Sjoystick_service](https://user-images.githubusercontent.com/31440972/156066782-920e0d47-453a-4d6e-88c6-e1f3a5e560b7.png)

which looks good as well. However, pairing the PS4 joystick did not succeed. So I run  `sudo hciconfig hci0 up ` as you mentioned in a doc, restart the PI and still no pairing.... I do not know how to debug this bluetooth stuff to be honest... and not familiar with it as well.

I ran hciconfig -a and here  is the result:
![inquiry](https://user-images.githubusercontent.com/31440972/156068403-82e64539-ad44-450e-8cf2-2343bcf2ecb9.png)

So if you can suggest some hint, I will be more than happy

Otherwise, because I would like to see this robot working, how can I test it without the joystick? 

I ran also `sudo systemctl status robot` and I noticed some modules did not match the runtime version, is it something to consider or not?
![robot_service](https://user-images.githubusercontent.com/31440972/156067578-3ed10e7b-614b-45c9-96db-81abf674726b.png)

Thanks for your support

**Comment by mangdangroboticsclub** [comment]
Hi FaBoNo,

I guess your question relates to the controller usage but not the source code issues, please double confirm the controller usage( https://mangdang-minipupperdocs.readthedocs-hosted.com/en/latest/guide/Operation.html ). 

By the way, I updated the calibration guide, please download the new image
20220302_v1.9.0_MiniPupper_V2_PS4_Ubuntu_21.10.0.img.zip

https://drive.google.com/drive/folders/12FDFbZzO61Euh8pJI9oCxN-eLVm5zjyi

It's better to discuss this kind of question on the FaceBook group( https://www.facebook.com/groups/716473723088464 ) but not here. If you can not use FaceBook, could you please let us know your back number and send us a mail to sales@mangdang.net?


Thanks!

**Comment by M352005** [comment]
PS4 joystic can be connected:

**sudo bluetoothctl
	agent on
	default-agent	
	power on
	pairable on**

_now press Share button on PS4 and keep holding it press PlayStation button for ~3 sec until PS4 power on and LED is blinking and continue with code:_

	scan on
_Keep scanning till see "Wireless Controller". Copy it address looking like хх:хх:хх:хх:хх:хх_

	pair хх:хх:хх:хх:хх:хх
	connect хх:хх:хх:хх:хх:хх
	trust хх:хх:хх:хх:хх:хх
	exit
