### ISSUE TITLE
Running into 'Servos overload please check' issue

### ISSUE THREAD

**Issue by gshiva** [mangdangroboticsclub/QuadrupedRobot#40]
After many attempts in assembly, I got the mini pupper assembled. After fixing wifi and figuring out how to run calibrate_tool from the command line, I am running into the 'servos overload please check' issue.

https://github.com/mangdangroboticsclub/QuadrupedRobot/blob/32e3b18a2d50e24256dab52251149884d9c1164a/StanfordQuadruped/calibrate_tool.py#L359 

Any suggestions?

I am using the [(64bit)v1.0.0.20220219.MiniPupper_V2_ROS&OpenCV_Ubuntu20.04.03.img.zip](https://drive.google.com/file/d/1gxisQQCIXHLqBpFs_-yun-ajLsee6gy8/view?usp=sharing)  image.

**Comment by mangdangroboticsclub** [comment]
That means your servo horn position is not right, please refer to the below calibration guide,
https://minipupperdocs.readthedocs.io/en/latest/guide/Software.html#calibration
(remove the 4 legs before calibration)
Thanks!

**Comment by gshiva** [comment]
Thanks will try it and will close the issue with instructions on what worked

**Comment by mangdangroboticsclub** [comment]
Please join our discord channel for better support, thanks!
https://discord.gg/enSJfUaV
