### ISSUE TITLE
Link needed for the right screwdrivers for attaching the servos

### ISSUE THREAD

**Issue by gshiva** [mangdangroboticsclub/QuadrupedRobot#41]
I force fit the servos (the central ones)as I didn't have the right screwdrivers. 

Links to the right sized screwdriver (sets are ok too) would help folks like me.

**Comment by mangdangroboticsclub** [comment]
Hi Gshiva,
We already put the tools in the kit, your question is the first time to me.
Could you please take a picture and send us a mail to sales@mangdang.net, we will give you feedback by mail.
Thanks!
