### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by FaboNo** [mangdangroboticsclub/QuadrupedRobot#44]
Hi there,

I am digging in the code but I do see that there are two .so files and no source code associated, can you tell me hay it is like this? Also what is the content of GaitScheme.so ?
Thank you for your help
Regards

**Comment by mangdangroboticsclub** [comment]
Already used the source code to replace the *.so file, please double confirm, thanks!

**Comment by sskorol** [comment]
@mangdangroboticsclub [Controller](https://github.com/mangdangroboticsclub/QuadrupedRobot/blob/MiniPupper_V2/StanfordQuadruped/src/Controller.py#L2) imports `GaitScheme` which is absent in `src` dir.
