### ISSUE TITLE
password and link not working

### ISSUE THREAD

**Issue by FeAlias** [mangdangroboticsclub/QuadrupedRobot#46]
I tried using the preinstalled image, but clicking on it says page not found. I tried installing through Etcher and it says incorrect login when I use ubuntu as the username and mangdang for the password. Thanks for the help. I am really excited about using this!

**Comment by mangdangroboticsclub** [comment]
Sorry, I forgot to update the download link for the new image file, I updated the download link, please download the new image file to try, thanks!
20220720_v2.0.1_MiniPupper_V1&V2_Controller_Ubuntu_22.04.img

**Comment by FeAlias** [comment]
Thank you!

**Comment by FeAlias** [comment]
Mind if I email you? I have an additional question you may be able to help with.
