### ISSUE TITLE
Error in SLAM installation guide Section 1.1.1

### ISSUE THREAD

**Issue by gilaramirez** [mangdangroboticsclub/QuadrupedRobot#47]
The code snippet should read as below (edits in bold text):

cd ~
sudo apt-get update
sudo apt-get install -y python3-wstool python3-rosdep ninja-build stow
mkdir carto_ws
cd carto_ws
wstool init src
wstool merge -t src https://raw.githubusercontent.com/cartographer-project/cartographer_ros/master/cartographer_ros.rosinstall
wstool update -t src
sudo rosdep init
rosdep update
rosdep install --from-paths src --ignore-src --rosdistro=**noetic**-y
src/cartographer/scripts/install_abseil.sh
**source /opt/ros/noetic/setup.bash**
sudo apt-get remove ros-${ROS_DISTRO}-abseil-cpp
catkin_make_isolated --install --use-ninja
source install_isolated/setup.bash

Otherwise cartographer_ros will not install.

**Comment by sskorol** [comment]
I believe folks intentionally omit sourcing ROS distro as this line should be put into your bash profile. Otherwise, you'll have a hard time sourcing it for every project you have.

**Comment by gilaramirez** [comment]
Unfortunately not including the ROS distro at that early stage fails the installation process.  As a matter of fact, following the rest of the SLAM install steps after resolving these still results in a broken installation.  I also found and tried to follow the steps in /src/minippoer_ros/README.md and those steps also failed.

Does anyone have a set of instructions for installation of SLAM?

During running of 

`$ catkin_make_isolated --install --use-ninja`

results in 
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GMOCK_LIBRARY
    linked by target "time_conversion_test" in directory /home/gil/carto_ws/src/cartographer_ros/cartographer_ros
    linked by target "configuration_files_test" in directory /home/gil/carto_ws/src/cartographer_ros/cartographer_ros
    linked by target "msg_conversion_test" in directory /home/gil/carto_ws/src/cartographer_ros/cartographer_ros
    linked by target "metrics_test" in directory /home/gil/carto_ws/src/cartographer_ros/cartographer_ros

-- Configuring incomplete, errors occurred!'

**Comment by mangdangroboticsclub** [comment]
Please try the auto-install command below, thanks!
$sudo apt-get install ros-noetic-cartographer-ros
If you still have questions, please put your issues on the mini_pupper_ros repo, thanks!
