### ISSUE TITLE
Code Of  ROS

### ISSUE THREAD

**Issue by happinessandlove** [mangdangroboticsclub/QuadrupedRobot#5]
I read the code of this project, but I did not find code about ROS? Could you tell me where can I find?

**Comment by mangdangroboticsclub** [comment]
Thanks for reaching out!
Now Github version is only the basic version, you can test it the basic movement performance.
We are updating ROS version, will release the source code after our Kickstarter campaign.
Best Regards,
Afreez

**Comment by happinessandlove** [comment]
Thank you very much~
