### ISSUE TITLE
What are the specs of the Servo?

### ISSUE THREAD

**Issue by bitsam** [mangdangroboticsclub/QuadrupedRobot#6]
What are the specs of the servo, if someone customises their build and needs to increase the power-weight ratio proportionally?

**Comment by mangdangroboticsclub** [comment]
We will release the servo spec after the campaign, thanks!

**Comment by mhered** [comment]
Check out [this link](https://drive.google.com/file/d/1HXJAASamHH5H4fXvL9rG8V1b8EakX5UQ/view)

**Comment by bitsam** [comment]
Thank you
