### ISSUE TITLE
Estimated maximum payload?

### ISSUE THREAD

**Issue by Camilochiang** [mangdangroboticsclub/QuadrupedRobot#8]
And estimated available voltages on board?
Thanks!

**Comment by mangdangroboticsclub** [comment]
7.4V, thanks!

**Comment by Camilochiang** [comment]
Thanks you! I will like to mark the issue as closed but im missing an estimated max payload? Thanks!!

**Comment by mangdangroboticsclub** [comment]
500g is OK.
