### ISSUE TITLE
Have you plan to create dock station? 

### ISSUE THREAD

**Issue by DisDis** [mangdangroboticsclub/QuadrupedRobot#9]
Dockstation for battery charging and auto docking(as robo vacuum cleaner)

**Comment by mangdangroboticsclub** [comment]
Yes, the dock station is always on our pipeline, we discussed it several times, but we have not enough time to finish it on Mini Pupper, will try to implement this feature in the feature.
Thanks for your advice, we will continue to update the software and hardware.

**Comment by mangdangroboticsclub** [comment]
If anyone has the dock station experience and try to implement on Mini Pupper, please send us a mail to afreez@mangdang.net 
Thanks!
